BP-1262: Small codebase improvements
MOV-AI/movai-core-shared pull request #179
Opened 2024-12-20 11:06 UTC by andreparames

Just some code cleanup, particularly functions that have incorrect typing hints. No change in behavior is expected.

Ticket: [BP-1262](https://movai.atlassian.net/browse/BP-1262)

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
~~- [ ] Link to relevant pull requests, esp. upstream and downstream changes~~
~~- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2024-12-23 12:54 UTC, diasdm requested changes
Great work, left a few comments

2024-12-23 12:54 UTC, diasdm commented on movai_core_shared/common/time.py
> +def delta_time_float(delta: timedelta) -> float:
Missing update to doc string

2024-12-23 12:54 UTC, diasdm commented on movai_core_shared/core/message_client.py
> +        self._zmq_client = cast(
Why cast?

2024-12-23 12:54 UTC, diasdm commented on movai_core_shared/core/message_client.py
> +        self,
Missing updates to docstring

2024-12-23 12:54 UTC, diasdm commented on movai_core_shared/core/zmq/zmq_client.py
> +                self._logger.warning(f"Resetting ZMQ {self._addr} with potential data loss.")
Maybe use leave interpolation to the logging function? https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-fstring-interpolation.html

2024-12-23 12:54 UTC, diasdm commented on movai_core_shared/core/zmq/zmq_helpers.py
> +def extract_reponse(buffer: List[bytes]) -> dict:
Docstring

2024-12-23 12:54 UTC, diasdm commented on movai_core_shared/core/zmq/zmq_server.py
> +            assert self._socket
Should this validation be closer to where self._socket is set?

2025-01-24 11:24 UTC, andreparames commented on movai_core_shared/core/message_client.py
> +        self._zmq_client = cast(
It's just to help static type analyzers understand the type that ZMQManager returns; it doesn't actually have any effect on runtime behavior.

2025-01-24 11:29 UTC, andreparames commented on movai_core_shared/core/zmq/zmq_server.py
> +            assert self._socket
The purpose is to help static type analyzers again; we're telling it to ignore the cases when `self._socket` is None, otherwise we'd have to add checks for None throughout the function.

2025-01-29 15:33 UTC, diasdm reviewed
Version bump and add to changelog?

2025-01-30 09:57 UTC, andreparames commented
> Version bump and add to changelog?

Thanks! Done.

2025-01-30 10:12 UTC, diasdm approved these changes

2025-01-30 10:12 UTC, merged