Feature/bp 255/intergrating the spawner
MOV-AI/movai-core-shared pull request #29
Opened 2022-12-28 08:13 UTC by engdorm

integrating the new flow-inititator

2022-12-28 08:59 UTC, erezz-mov-ai commented on movai_core_shared/envvars.py
> +MOVAI_MSG_SERVER_PORT = os.getenv("MOVAI_MSG_SERVER_PORT", "8082")
MSG SERVER PORT IS configured for 8081

2022-12-28 09:00 UTC, erezz-mov-ai commented on movai_core_shared/envvars.py
> +MOVAI_ZMQ_TIMEOUT_MS = os.getenv("MOVAI_ZMQ_TIMEOUT_MS", "10000")
you didn't use the timeout in your ZMQClient code

2023-01-02 12:35 UTC, Mograbi approved these changes

2023-02-14 13:04 UTC, AlexFernandes-MOVAI requested changes
please resolve conflicts

2023-12-12 11:36 UTC, closed without merging